### ISSUE TITLE
Support tweetdeck

### ISSUE THREAD

**Issue by natir** [MarcBrillault/twitter-anonymizer#24]
First nice job.

After small research it's seems, tweetdeck and twitter didn't use any `id` or `class` in common, sorry.

**Comment by MarcBrillault** [comment]
Tweetdeck's classes and IDs seem a LOT easier to use, it shouldn't be too hard.

**Comment by MarcBrillault** [comment]
@natir tweetdeck support has been added!
Firefox plugin is up-to-date, chrome will follow... and for Opera, I'll wait until they validated the previous version.
