### ISSUE TITLE
Manifest url matches: missing mobile.twitter case.

### ISSUE THREAD

**Issue by JohnXLivingston** [MarcBrillault/twitter-anonymizer#7]
Is your extension compatible with Firefox mobile?
If yes, I think there should be a missing case here:

https://github.com/MarcBrillault/twitter-anonymizer/blob/4b8191206d7d65d71b2972fa2470e83f43660c2f/manifestv2/manifest.json#L15-L17

On mobile, twitter url is `https://mobile.twitter.com`.

**Comment by MarcBrillault** [comment]
Oh, you're right, I should update that, thanks.
